### ISSUE TITLE
Create a release/tag to use as cocoapods dependency

### ISSUE THREAD

**Issue by ararog** [Isuru-Nanayakkara/Swift-Reachability#5]
Hi,

While cocoapods 0.36 doesn't have an official release, it would be nice to have a tag based on master branch and then add Swift-Reachability as reference in my project.

Like podspec says, I believe the tag should be named 0.1.0, just guessing, if not, please make sure both match with the same version.

**Comment by Isuru-Nanayakkara** [comment]
Hi,
Forgive me, can you please elaborate what I need to do? Currently you can add the following line to your `Podfile` and install the library via CocoaPods.

`pod 'Swift-Reachability', :git => 'https://github.com/Isuru-Nanayakkara/Swift-Reachability.git'`

**Comment by ararog** [comment]
You is right, in fact a tag isn't required whille 0.36 isn't released.
